### ISSUE TITLE
[Suggestion] Execute Commands

### ISSUE THREAD

**Issue by Xarmat-GitHub** [jredfox/norespawnscreen#12]
This Mod is pretty handy, thanks for the effort you put in. 👍 

Here is my suggestion:
- When the player dies, execute a list of commands

Opportunities:
- Commands can be used to trigger something
- Game Stages can be changed
- Mods can Teleport the player to a respawn location (not to his bed) [Story / Lore]

Mechanic:
- Execute Commands as Player or Server
- Execute Commands Silent / Loud in Chat

Optional - When Possible:
- Allow Commands while the player is death (not respawn yet for some frames) - Enable things like spawning a Block where he died / Explode / Spawn Particles / Post Location in Chat / etc.

Would love to see this, at the moment I have to find an workaround to get the player back to the Starting Dimension when he die ( and not to his Bed).

**Comment by jredfox** [comment]
so the mod is broken af if you didn't notice half the time when steve dies it glitches. secondly it uses reflection not even access transformer. this mod is legacy shit. I don't plan on fixing it anytime soon.

As for your issue specifically it's more to add a forge specific event. for my mod loader I plan on making a solution for forge events to be even more mod cross compatible but, I haven't started work on that yet. It maybe two months before I even get to start on the mod loader itself due to irl issues, health issues, and omni archive projects

It's not really an issue with the mod. you could code things on player death event or something to fire code for a custom event if you know basic java and ide tracing from there do whatever you want to do in that code including executing commands.
